### ISSUE TITLE
Multiple entries for for log_group

### ISSUE THREAD

**Issue by kishorramanan** [lukewaite/logstash-input-cloudwatch-logs#13]
Hi, 

We have the following log_group patterns _/aws/lambda/app-name
Can we have input
`log_group  => ["logname1", "logname2"]`
does not work

Logstash version: 5.1

**Comment by lukewaite** [comment]
Hi @kishorramanan - I've just merged in #9 which allows you to use a prefix for importing multiple log groups.

Does that meet your need?

**Comment by KIVagant** [comment]
@lukewaite , error with config:
```
input {
   cloudwatch_logs {
     access_key_id => "123"
     secret_access_key => "456"
     region => "us-east-1"
     log_group_prefix => "myprefix"
   }
 }
```

Log output:
```
[2017-06-06T14:10:00,250][ERROR][logstash.inputs.cloudwatch_logs] Missing a required setting for the cloudwatch_logs input plugin:

  input {
    cloudwatch_logs {
      log_group => # SETTING MISSING
      ...
    }
  }
```

**Comment by lukewaite** [comment]
Hi there.

'log_group_prefix' is a Boolean, and instructs whether to treat the
required 'log_group' setting as an absolute or prefix.

**Comment by KIVagant** [comment]
Ok, thank you.

**Comment by lukewaite** [comment]
Sorry for the short response, and lack of formatting. Am travelling and only had access to email.

Did that work for you?

**Comment by KIVagant** [comment]
I didn't have a time to test this yet.

**Comment by lukewaite** [comment]
> And, it's still better to be able to set array of logs groups instead of prefix.
I'd be happy to accept a PR introducing this behaviour. 

I'm planning a rewrite, for a v1 release, and can likely include this. I can't offer a timeline yet, though.

**Comment by lukewaite** [comment]
@kishorramanan I've just tagged `v1.0.0.pre`, a pre-release which adds support for specifying an array of `log_group`s.

https://github.com/lukewaite/logstash-input-cloudwatch-logs/releases/tag/v1.0.0.pre
