### ISSUE TITLE
dynamic log group discovery?

### ISSUE THREAD

**Issue by joemiller** [lukewaite/logstash-input-cloudwatch-logs#2]
I think it would be great if the plugin would discover all log groups or take a wildcard for log groups (I am thinking something like `/aws/lambda/*`) so that all new lambdas that are deployed will automatically be consumed.

Do you see any issues with this functionality? I see the open issue about rate-limiting that I suspect would be even bigger of a concern with something like this.

**Comment by lukewaite** [comment]
Sorry for the extremely long lack of activity on this project.

I have received a patch from a user that implements this functionality, however I'm unsure that it's ready for prime time. I've opened a PR here: https://github.com/lukewaite/logstash-input-cloudwatch-logs/pull/7

I've mentioned my concerns in that PR. If you have any feedback on how to implement it would be appreciated.
