### ISSUE TITLE
Error: uninitialized constant OpenSSL

### ISSUE THREAD

**Issue by lisajluo** [lukewaite/logstash-input-cloudwatch-logs#23]
Hello, getting the following error on the latest logstash-input-cloudwatch_logs (0.10.3):

logstash_1       |   Error: uninitialized constant #<Class:0x5192f7f2>::OpenSSL
logstash_1       | [2017-05-19T15:30:36,360][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
logstash_1       |   Plugin: <LogStash::Inputs::CloudWatch_Logs sincedb_path=>"###", log_group=>"###", tags=>["###"], id=>"#####", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_a82f1752-347a-4484-b6b8-8fbc5c2680c1", enable_metric=>true, charset=>"UTF-8">, region=>"us-east-1", interval=>60, log_group_prefix=>false>

**Comment by lukewaite** [comment]
This looks kind of similar to https://github.com/elastic/logstash/issues/4419

I wonder if this is tied to the lazy loading of `digest/md5` which currently happens in the `register` method.. https://github.com/lukewaite/logstash-input-cloudwatch-logs/blob/master/lib/logstash/inputs/cloudwatch_logs.rb#L52

I'll see if I can reproduce.

**Comment by lukewaite** [comment]
@lisajluo I'm unable to reproduce in the `logstash:5.4.0` docker image.

What version of logstash are you running?
What JVM?
What OS?

Are you able to provide specific steps to reproduce?

Thanks

**Comment by lisajluo** [comment]
@lukewaite I'm using the `logstash:5.3.0` docker image (running Docker for Mac). Will try `5.4.0` too (there are some build differences so it may take me some time to resolve)

On `5.3.0` I'm just running `logstash-plugin install logstash-input-cloudwatch_logs` with some pretty basic logstash configs:

```
input {
    cloudwatch_logs {
        sincedb_path => "/usr/share/logstash/.sincedb/valora"
        log_group => "/opt/haven/logs/valora.log"
        tags => ["pre-convox"]
    }
}
```

**Comment by lisajluo** [comment]
Sorry for the delay - just got back to this - was still seeing this on `logstash:5.5.2`. I did notice that we had some log streams with commas (`app1,app2`) in the name - since those streams are no longer in use, I removed them and did not run into this error any further. Closing unless I see it again. Thanks!
