### ISSUE TITLE
Docker AWS Logging driver

### ISSUE THREAD

**Issue by abzmungul** [lukewaite/logstash-input-cloudwatch-logs#24]
When using the AWS Logging driver, each container creates a log stream within a log group, if a container moves to a different host or gets re provisioned it creates a new log stream, what this results in is lots of log streams being generated.

Whilst running logstash in debug mode I can see that the recursive statement tries to read and parse all the log streams created before it runs out of memory and fails

:message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::CloudWatch_Logs region=>\"eu-west-1\"

How have others solved this problem?

**Comment by marek-obuchowicz** [comment]
I'm running it at the moment with 1GB allocated for JVM heap. Didn't get "out of memory" issue yet, but I experience that it has *terrible* performance - scanning various log streams is very slow, as it takes as much as 200ms per stream to process. We'll still give it a try, but seems like this plugin is not useful for us. As another alternative I consider creating lambda function that reads from CloudWatch Logs and puts events to redis list, then use logstash to retrieve events from there.

**Comment by abzmungul** [comment]
We have a 1g heap too. Would be interesting to see if anyone else is getting similar issues

**Comment by lukewaite** [comment]
@abzmungul Are you ingesting a single log group? Or are you using the ingest by prefix mode? 

The plugin has largely not needed to be touched since it was written; there's definitely room for performance improvements. I've been meaning to begin a refactor. Will see how much headway I can make today while travelling.

**Comment by marek-obuchowicz** [comment]
@lukewaite for case with AWS ECS, each container creates a new stream in the same log group. If you're unlucky and push there container which fails to start - it will be restarted in endless loop and it's not uncommon that such container will create several thousands of streams under one log group

**Comment by abzmungul** [comment]
@marek-obuchowicz so this is exactly the issue :)

**Comment by lukewaite** [comment]
Ah - Thanks! I haven't run in production against ECS as the log source myself, so hadn't considered the possibility of a failing container in a service generating thousands of streams.

I thought I had a pretty good test case with lambdas generating a few hundred streams a day...

Ok, I have some thoughts on how to re-structure to improve performance.. Will see how it goes.

**Comment by lukewaite** [comment]
I've just tagged `v1.0.0.pre`, a pre-release which fixes a few memory leaks that I think were the culprit here.

I'd appreciate any feedback, initial testing on my end looks good.

https://github.com/lukewaite/logstash-input-cloudwatch-logs/releases/tag/v1.0.0.pre
