### ISSUE TITLE
Error && "Initialize: name or service not known"

### ISSUE THREAD

**Issue by flypenguin** [lukewaite/logstash-input-cloudwatch-logs#30]
First, thanks for the plugin. Second, I just tried it with logstash 5.4.2 running in a [container](https://github.com/CognotektGmbH/docker-logstash) (the official one from elastic.co, with the plugin installed as described in the [blog post](https://lukewaite.ca/aws/lambda/elk/logstash/2015/07/13/aws-lambda-and-elk.html)), and ran into the following issue:

```
Jul 07 15:19:32 ip-10-10-15-13 docker[27906]: 13:19:32.212 [[main]<cloudwatch_logs] ERROR logstash.pipeline - A plugin had an unrecoverable error. Will restart this plugin.
Jul 07 15:19:32 ip-10-10-15-13 docker[27906]:   Plugin: <LogStash::Inputs::CloudWatch_Logs type=>"elasticbeanstalk", region=>"eu-central-1", log_group=>["/aws/elasticbeanstalk/"], log_group_prefix=>true, interval=>30, id=>"c667b4b34c50753165191cd8ff63292b06b5a5c7-2", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_2acad102-83e1-4aa2-accf-6ae5ffad62f9", enable_metric=>true, charset=>"UTF-8">, start_position=>"beginning">
Jul 07 15:19:32 ip-10-10-15-13 docker[27906]:   Error: initialize: name or service not known
```

I have no clue what this is, but I guess it's not working. :)

**Comment by lukewaite** [comment]
The error you're getting is a DNS error saying it can't find the CloudWatch Logs region endpoint for `eu-central-1`. 

Everything _should_ just play nice together, as that region setting is passed through when constructing the CloudWatch Logs client.

Is it possible that the container you're running in is experiencing networking issues? Are you able to hit the endpoint via another method? eg `curl -I logs.eu-central-1.amazonaws.com`

**Comment by flypenguin** [comment]
actually I can't reproduce the issue any more. closing.
