### ISSUE TITLE
Allow providing aws profile name instead of aws key and secret key

### ISSUE THREAD

**Issue by aleybovich** [lukewaite/logstash-input-cloudwatch-logs#39]
Currently you need to provide access key and secret key to the account where cloudwatch is. Can we add an option to provide just the aws profile name of the profile setup on the logstash server and the plugin would be getting access_key and secret_key from that profile? Same way as terraform does it. 
We store logstash.config in code repository and for obvious security reasons we don't want to store secret keys there.

**Comment by lukewaite** [comment]
We could implement this on our own, but I'd really rather not.

AWS authentication in logstash is typically provided by a shared library called `logstash-mixin-aws`.

If we break with the convention, we'll be forced to support it on our own, and will have a different experience than any other plugin.

There's a PR for this enhancement open on the mixin, so I'd request that you register your feedback there: https://github.com/logstash-plugins/logstash-mixin-aws/pull/27

**Comment by lukewaite** [comment]
Sorry - I linked to the wrong issue. There's an issue open for this particular use case, but no PR.

https://github.com/logstash-plugins/logstash-mixin-aws/issues/29

**Comment by lukewaite** [comment]
[v1.0.3](https://github.com/lukewaite/logstash-input-cloudwatch-logs/releases/tag/v1.0.3) has just been tagged which updates to [logstash-mixin-aws 4.3.0](https://github.com/logstash-plugins/logstash-mixin-aws/blob/master/CHANGELOG.md#430) which should solve this issue.

**Comment by lvthillo** [comment]
@lukewaite Do we need additional config? I've removed the access key configuration + installed latest version of the plugin and I have an instanceprofile connected to my ec2 (where logstash is running): but still got this
`Error: unable to sign request without credentials set
`

Only cloudwatch logs are not coming through so it seems logstash is picking up the credentials from the role (instanceprofile) but the plugin doesn't?
