### ISSUE TITLE
Is this plugin added to Logstash Plugin Repo

### ISSUE THREAD

**Issue by maheshshekhar** [lukewaite/logstash-input-cloudwatch-logs#40]
Hello Team,

Is this plugin added to Logstash Plugin Repo. Also, can you please provide the information on using the plugin. How we will need to install the plug in and ho we can use it to take the cloudwatch logs.

Regards,

**Comment by lukewaite** [comment]
Hi @maheshshekhar - this plugin is not part of the `logstash-plugins` repo, but it is published to RubyGems, so you can install as you would [any logstash plugin](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html).

bin/logstash-plugin install logstash-input-cloudwatch_logs

Configuration is as per the documented input parameters, again, like any other logstash plugin:
https://github.com/lukewaite/logstash-input-cloudwatch-logs#parameters

**Comment by maheshshekhar** [comment]
Thanks Luke, It works..This is very useful.

**Comment by lukewaite** [comment]
Wonderful, happy to hear that!
