### ISSUE TITLE
start_postion is not working

### ISSUE THREAD

**Issue by di1214** [lukewaite/logstash-input-cloudwatch-logs#43]
https://github.com/lukewaite/logstash-input-cloudwatch-logs/blob/master/lib/logstash/inputs/cloudwatch_logs.rb#L173

this line of code failed to convert DateTime.now.strftime('%Q') to integer, which is causing problem "-" not defined. I have a fix locally 
`timeNow = DateTime.now.strftime('%Q')
  sincedb[group] = timeNow.to_i - (@start_position * 1000)
`
could you please take a look and fix it?

**Comment by lukewaite** [comment]
This is resolved in the just released v1.0.2.
