### ISSUE TITLE
Through the aws role can not get cloudwatch logs

### ISSUE THREAD

**Issue by Gitnichub** [lukewaite/logstash-input-cloudwatch-logs#45]
configuration:

input {
	cloudwatch_logs {
	        log_group => "CloudTrail/DefaultLogGroup"
		region => "us-east-1"
		id => "CloudTrail_log"
		tags => "CloudTrail_log"
	}
}

output {
    elasticsearch {
      hosts => ["x.x.x.x"]
      index => "test-%{+YYYY.MM.dd}"
    }
}

Logstash log can be seen, log_group is correct

**Comment by lukewaite** [comment]
If this is still an ongoing issue, could you please re-open and provide some of the log output in debug mode?
