### ISSUE TITLE
issue while installing the plugin

### ISSUE THREAD

**Issue by sunilmchaudhari** [lukewaite/logstash-input-cloudwatch-logs#68]
Hi
I followed the steps https://github.com/lukewaite/logstash-input-cloudwatch-logs/blob/master/DEVELOPER.md#21-run-in-a-local-logstash-clone

When execute command /bin/logstash-plugin install logstash-input-cloudwatch-2.2.4.gem

then it shows error ERROR: Something went wrong when installing logstash-input-cloudwatch-2.2.4.gem, message: Failed to open TCP connection to artifacts.elastic.co:443 (execution expired)

We don't have internet connection from the server
How to install offline. please send instructions step by step.

**Comment by ksemaev** [comment]
@sunilmchaudhari you can install plugin on stage logstash with internet access, and then move it to prod: https://www.elastic.co/guide/en/logstash/current/offline-plugins.html

Basicaly your issue has nothing to do with this repo, it's basic knowlege of logstash's management
